all:
  hosts:
    master-1:
      vars_files:
        - vars.yml
      vars:
        ansible_ssh_private_key_file: "{{ key1 }}"
      ansible_host: 84.201.154.151
      ip: 192.168.20.24
      access_ip: 192.168.20.24
      ansible_user: motorher
    worker-1:
      vars_files:
        - vars.yml
      vars:
        ansible_ssh_private_key_file: "{{ key1 }}"
      ansible_host: 51.250.111.41
      ip: 192.168.20.6
      access_ip: 192.168.20.6
      ansible_user: motorher
    worker-2:
      vars_files:
        - vars.yml
      vars:
        ansible_ssh_private_key_file: "{{ key1 }}"
      ansible_host: 89.169.172.37
      ip: 192.168.20.15
      access_ip: 192.168.20.15
      ansible_user: motorher
  children:
    kube_control_plane:
      hosts:
        master-1:
    kube_node:
      hosts:
        worker-1:
        worker-2:
    etcd:
      hosts:
        master-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}